#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3

teamname="CLSF"

cd $BASEDIR

options="--team_name $teamname --server-host $HOST --use-random-rpc-port --auto-close-rpc-server --disable-log-file"

case $NUM in
    1)
        ./start.bin $options --goalie
        ;;
    12)
        ./start.bin $options --coach
        ;;
    *)
        ./start.bin $options --player
        ;;
esac